import { DashboardStats } from "@/model/dashboard-stat";
import {
  addDoc,
  collection,
  db,

  serverTimestamp,

} from "@/config/firebase"

import { Activity } from "@/model/dashboard-stat";


export const addNewActivity = async (
  activity: Activity
): Promise<boolean> => {
  try {
    await addDoc(collection(db, "activities"), {
      ...activity,
      timestamp: serverTimestamp(), // generated by Firestore
    })

    return true
  } catch (error) {
    console.error("Error adding activity:", error)
    return false
  }
}